# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' )
#   Mayor.create(name: 'Emanuel', city: cities.first)

Schedule.create(name: '7:00 am - 8:30 am (1,3)')
Schedule.create(name: '8:30 am - 10:00 am (1,3)')
Schedule.create(name: '10:00 am - 11:30 am (1,3)')
Schedule.create(name: '3:00 pm - 4:30 pm (1,3)')
Schedule.create(name: '4:30 pm - 6:00 pm (1,3)')
Schedule.create(name: '6:00 pm - 7:30 pm (1,3)')
Schedule.create(name: '7:30 pm - 9:00 pm (1,3)')
Schedule.create(name: '7:00 am - 8:30 am (2,4)')
Schedule.create(name: '8:30 am - 10:00 am (2,4)')
Schedule.create(name: '10:00 am - 11:30 am (2,4)')
Schedule.create(name: '3:00 pm - 4:30 pm (2,4)')
Schedule.create(name: '4:30 pm - 6:00 pm (2,4)')
Schedule.create(name: '6:00 pm - 7:30 pm (2,4)')
Schedule.create(name: '7:30 pm - 9:00 pm (2,4)')
Schedule.create(name: '7:00 am - 8:30 am (5)')
Schedule.create(name: '8:30 am - 10:00 am (5)')
Schedule.create(name: '10:00 am - 11:30 am (5)')
Schedule.create(name: '3:00 pm - 4:30 pm (5)')
Schedule.create(name: '4:30 pm - 6:00 pm (5)')
Schedule.create(name: '6:00 pm - 7:30 pm (5)')
Schedule.create(name: '6:00 pm - 9:00 pm (5)')
Schedule.create(name: '7:30 am - 10:30 am (6)')
Schedule.create(name: '10:30 am - 1:30 pm (6)')
Schedule.create(name: '1:30 pm - 4:30 pm (6)')
Schedule.create(name: '4:30 pm - 7:30 pm (6)')
Schedule.create(name: '7:30 am - 10:30 am (7)')
Schedule.create(name: '10:30 am - 1:30 pm (7)')
Schedule.create(name: '2:00 pm - 5:00 pm (7)')

State.create(name: 'Pendiente')
State.create(name: 'Confirmado')
State.create(name: 'Cancelado')

Course.create(name:'Expresión Oral', requirements: 'Español', recommended_requirements: 'n/a')
Course.create(name:'Introducción al Diseño',	requirements: 'n/a',	recommended_requirements: 'n/a')
Course.create(name:'Redacción', requirements: 'Expresión Oral',	recommended_requirements: 'n/a')
Course.create(name:'Fund. Teorías Comunicación',	requirements: 'n/a',	recommended_requirements: 'n/a')
Course.create(name:'Comp. Aplic. Diseño Gráfico',	requirements: 'n/a',	recommended_requirements: 'n/a')
Course.create(name:'Intro. Medios Visuales',	requirements: 'Fund. Teorías Comunicación',	recommended_requirements: 'n/a')
Course.create(name:'Dibujo',	requirements: 'n/a',	recommended_requirements: 'n/a')
Course.create(name:'Proyecciones Geométricas',	requirements: 'Álgebra',	recommended_requirements: 'n/a')
Course.create(name:'Psicología del Diseño',	requirements: 'Intro. Diseño Gráfico',	recommended_requirements: 'n/a')
Course.create(name:'Comunicación Gráfica I',	requirements: 'Intro. Al Diseño Gráfico y Dibujo', recommended_requirements: 'Comp. Aplic. Diseño Gráfico')
Course.create(name:'Semiótica', requirements:'Psicología del Diseño', recommended_requirements: 'n/a')
Course.create(name:'Fotografía', requirements: 'Comunicación Gráfica I', recommended_requirements: 'n/a')
Course.create(name:'Dibujo Avanzado', requirements: 'Comunicación Gráfica', recommended_requirements: 'n/a')
Course.create(name:'Comunicación Gráfica II',	requirements: 'Fotografía y Dibujo Avanzado',	recommended_requirements: 'n/a')
Course.create(name:'Creatividad Publicitaria',	requirements: 'Publicidad',	recommended_requirements: 'n/a')
Course.create(name:'Tipografía',	requirements: 'Fotografía Comercial y Semiótica',	recommended_requirements: 'n/a')
Course.create(name:'Fotografía Comercial',	requirements: 'Fotografía',	recommended_requirements: 'n/a')
Course.create(name:'Tec. Expresión e Ilustración',	requirements: 'Comunicación Gráfica II',	recommended_requirements: 'n/a')
Course.create(name:'Edición de Impresos',	requirements: 'Fotografía Comercial y Creatividad Publicitaria',	recommended_requirements: 'n/a')
Course.create(name:'Imagen Corporativa',	requirements: 'Publicidad',	recommended_requirements: 'n/a')
Course.create(name:'Nuevas Tecnologías Diseño Gráfico',	requirements: 'Tec. Expresión e Ilustración',	recommended_requirements: 'n/a')
Course.create(name:'Diseño y Producción de Etiquetas, Envases y Empaques',	requirements: 'Creatividad Publicitaria',	recommended_requirements: 'n/a')
Course.create(name:'Admon. Materiales y Costos de Impresión',	requirements: 'Diseño y Producción de Etiquetas, Envases y Empaques',	recommended_requirements: 'n/a')
Course.create(name:'Campañas de Divulgación',	requirements: 'Creatividad Publicitaria',	recommended_requirements: 'n/a')
Course.create(name:'Diseño Editorial',	requirements: 'Edición de Impresos',	recommended_requirements: 'n/a')
Course.create(name:'Diseño Gráfico y Animación por Computadora',	requirements: 'Artes Finales',	recommended_requirements: 'n/a')
Course.create(name:'Producciones de Artes Gráficas',	requirements: 'Diseño Producción de Etiquetas, Envases y Empaques',	recommended_requirements: 'n/a')
Course.create(name:'Técnicas de Grabado',	requirements: 'Artes Finales',	recommended_requirements: 'n/a')
Course.create(name:'Diseño para Multimedia',	requirements: 'Diseño Gráfico y Animación por Computadora',	recommended_requirements: 'n/a')
Course.create(name:'Señalética',	requirements: 'Producción de Artes Gráficas',	recommended_requirements: 'n/a')
Course.create(name:'Sistema de Impresión Serigráfica',	requirements: 'Técnicas de Grabado',	recommended_requirements: 'n/a')
Course.create(name:'Historia del Arte',	requirements: 'n/a',	recommended_requirements: 'n/a')
Course.create(name:'Metodología del Diseño',	requirements: 'Proyecciones Geométricas',	recommended_requirements: 'n/a')
